# ...

task3_scan_locations:
  - name: '1'
    location:
      position: { x: 0.5, y: 0.3, z: 0.6 }
      orientation: { x: -1.0, y: 0.0, z: 0.0, w: 0.0 }
    thresholds:
      x_thrs_min: 0.20
      y_thrs_min: 0.15
      x_thrs_max: 0.9
      y_thrs_max: 0.45
      
  - name: '2'
    location:
      position: { x: 0.5, y: 0.0, z: 0.6 }
      orientation: { x: -1.0, y: 0.0, z: 0.0, w: 0.0 }
    thresholds:
      x_thrs_min: 0.20
      y_thrs_min: -0.15
      x_thrs_max: 0.9
      y_thrs_max: 0.15

  - name: '3'
    location:
      position: { x: 0.5, y: -0.3, z: 0.6 }
      orientation: { x: -1.0, y: 0.0, z: 0.0, w: 0.0 }
    thresholds:
      x_thrs_min: 0.20
      y_thrs_min: -0.45
      x_thrs_max: 0.9
      y_thrs_max: -0.15

  - name: '4'
    location:
      position: { x: 0.233, y: -0.3, z: 0.6 }
      orientation: { x: -1.0, y: 0.0, z: 0.0, w: 0.0 }
    thresholds:
      x_thrs_min: 0.1
      y_thrs_min: -0.45
      x_thrs_max: 0.2
      y_thrs_max: -0.15
      
  - name: '5'
    location:
      position: { x: -0.033, y: -0.3, z: 0.6 }
      orientation: { x: -1.0, y: 0.0, z: 0.0, w: 0.0 }
    thresholds:
      x_thrs_min: -0.1
      y_thrs_min: -0.45
      x_thrs_max: 0.1
      y_thrs_max: -0.15

  - name: '6'
    location:
      position: { x: -0.3, y: -0.3, z: 0.6 }
      orientation: { x: -1.0, y: 0.0, z: 0.0, w: 0.0 }
    thresholds:
      x_thrs_min: -0.8
      y_thrs_min: -0.45
      x_thrs_max: -0.1
      y_thrs_max: -0.15

  - name: '7'
    location:
      position: { x: -0.3, y: 0.0, z: 0.6 }
      orientation: { x: -1.0, y: 0.0, z: 0.0, w: 0.0 }
    thresholds:
      x_thrs_min: -0.80
      y_thrs_min: -0.15
      x_thrs_max: -0.1
      y_thrs_max: 0.15
      
  - name: '8'
    location:
      position: { x: -0.3, y: 0.3, z: 0.6 }
      orientation: { x: -1.0, y: 0.0, z: 0.0, w: 0.0 }
    thresholds:
      x_thrs_min: -0.8
      y_thrs_min: 0.15
      x_thrs_max: -0.1
      y_thrs_max: 0.45

  - name: '9'
    location:
      position: { x: -0.033, y: 0.3, z: 0.6 }
      orientation: { x: -1.0, y: 0.0, z: 0.0, w: 0.0 }
    thresholds:
      x_thrs_min: -0.1
      y_thrs_min: 0.15
      x_thrs_max: 0.1
      y_thrs_max: 0.45

  - name: '10'
    location:
      position: { x: 0.233, y: 0.3, z: 0.6 }
      orientation: { x: -1.0, y: 0.0, z: 0.0, w: 0.0 }
    thresholds:
      x_thrs_min: 0.10
      y_thrs_min: 0.15
      x_thrs_max: 0.20
      y_thrs_max: 0.45



# ...

task3_scan_locations:
  - name: '1'
    location:
      position: { x: 0.5, y: 0.3, z: 0.6 }
      orientation: { x: -1.0, y: 0.0, z: 0.0, w: 0.0 }
    thresholds:
      x_thrs_min: 0.20
      y_thrs_min: 0.15
      x_thrs_max: 0.9
      y_thrs_max: 0.45
      
  - name: '2'
    location:
      position: { x: 0.5, y: 0.0, z: 0.6 }
      orientation: { x: -1.0, y: 0.0, z: 0.0, w: 0.0 }
    thresholds:
      x_thrs_min: 0.20
      y_thrs_min: -0.15
      x_thrs_max: 0.9
      y_thrs_max: 0.15

  - name: '3'
    location:
      position: { x: 0.5, y: -0.3, z: 0.6 }
      orientation: { x: -1.0, y: 0.0, z: 0.0, w: 0.0 }
    thresholds:
      x_thrs_min: 0.20
      y_thrs_min: -0.45
      x_thrs_max: 0.9
      y_thrs_max: -0.15

  - name: '4'
    location:
      position: { x: 0.233, y: -0.3, z: 0.6 }
      orientation: { x: -1.0, y: 0.0, z: 0.0, w: 0.0 }
    thresholds:
      x_thrs_min: 0.1
      y_thrs_min: -0.45
      x_thrs_max: 0.2
      y_thrs_max: -0.15
      
  - name: '5'
    location:
      position: { x: -0.033, y: -0.3, z: 0.6 }
      orientation: { x: -1.0, y: 0.0, z: 0.0, w: 0.0 }
    thresholds:
      x_thrs_min: -0.1
      y_thrs_min: -0.45
      x_thrs_max: 0.1
      y_thrs_max: -0.15

  - name: '6'
    location:
      position: { x: -0.3, y: -0.3, z: 0.6 }
      orientation: { x: -1.0, y: 0.0, z: 0.0, w: 0.0 }
    thresholds:
      x_thrs_min: -0.8
      y_thrs_min: -0.45
      x_thrs_max: -0.1
      y_thrs_max: -0.15

  - name: '7'
    location:
      position: { x: -0.3, y: 0.0, z: 0.6 }
      orientation: { x: -1.0, y: 0.0, z: 0.0, w: 0.0 }
    thresholds:
      x_thrs_min: -0.80
      y_thrs_min: -0.15
      x_thrs_max: -0.1
      y_thrs_max: 0.15
      
  - name: '8'
    location:
      position: { x: -0.3, y: 0.3, z: 0.6 }
      orientation: { x: -1.0, y: 0.0, z: 0.0, w: 0.0 }
    thresholds:
      x_thrs_min: -0.8
      y_thrs_min: 0.15
      x_thrs_max: -0.1
      y_thrs_max: 0.45

  - name: '9'
    location:
      position: { x: -0.033, y: 0.3, z: 0.6 }
      orientation: { x: -1.0, y: 0.0, z: 0.0, w: 0.0 }
    thresholds:
      x_thrs_min: -0.1
      y_thrs_min: 0.15
      x_thrs_max: 0.1
      y_thrs_max: 0.45

  - name: '10'
    location:
      position: { x: 0.233, y: 0.3, z: 0.6 }
      orientation: { x: -1.0, y: 0.0, z: 0.0, w: 0.0 }
    thresholds:
      x_thrs_min: 0.10
      y_thrs_min: 0.15
      x_thrs_max: 0.20
      y_thrs_max: 0.45

